package SynoptixAI.Pages;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

public class LinkedIn {
	WebDriver driver;
	WebDriverWait wait;
	private By connections=By.cssSelector("img[alt='Connections']");
	private By tools=By.xpath("//button[normalize-space()='Tools']");
	private By linkedInCon=By.cssSelector("p[title='Craft LinkedIn posts.']");
	private By addCon=By.xpath("(//button[normalize-space()='Add (1)'])[1]");
	private By newChatBtnLoc=By.xpath("//span[normalize-space()='New Chat']");
	private By promptFieldLoc=By.xpath("//textarea[@id='synoptix-message-input']");
	private By sendBtnLoc=By.cssSelector("img[alt='Send']");

	public LinkedIn(WebDriver driver) {
		this.driver = driver;
		this.wait = new WebDriverWait(driver, Duration.ofSeconds(30));

	}

	public void turnOnLinkedInTool() {

		WebElement newChatBtn=wait.until(ExpectedConditions.elementToBeClickable(newChatBtnLoc));
		newChatBtn.click();
		WebElement conBtn = wait.until(ExpectedConditions.elementToBeClickable(connections));
		conBtn.click();
		WebElement toolBtn = wait.until(ExpectedConditions.elementToBeClickable(tools));
		toolBtn.click();
		WebElement conLinkBtn=wait.until(ExpectedConditions.elementToBeClickable(linkedInCon));	
		conLinkBtn.click();
		WebElement addBtn = wait.until(ExpectedConditions.elementToBeClickable(addCon));
		addBtn.click();
	}
	
	public void createPost()
	{
	
		WebElement promptField=driver.findElement(promptFieldLoc);
		promptField.click();
		promptField.sendKeys("Create an employee spotlight post celebrating a team member’s 5-year anniversary and their contribution to company growth.");
		WebElement sendButton=driver.findElement(sendBtnLoc);
		sendButton.click();
		
	// Step 3: Wait for AI to generate Outlook button
        WebElement postButton = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[normalize-space()='Review and Post']")));
       // meetingLinkButton.click();
        Assert.assertTrue(postButton.isDisplayed(), "LinkedIn Post generated by AI!");

		
		
	}
	
	

}
