package SynoptixAI.Pages;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

public class Outlook {
	
	 WebDriver driver;
	 WebDriverWait wait;
	 
	private By connections=By.cssSelector("img[alt='Connections']");
	private By outlookCon=By.xpath("(//span[normalize-space()='Outlook'])[1]");
	private By addCon=By.xpath("(//button[normalize-space()='Add (1)'])[1]");
	private By promptFieldLoc=By.xpath("//textarea[@id='synoptix-message-input']");
	private By sendBtnLoc=By.cssSelector("img[alt='Send']");
	
	public Outlook(WebDriver driver) {
		this.driver = driver;
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(30));

		}

	public void turnOnOutlookCon() {
		
		WebElement conBtn = wait.until(ExpectedConditions.elementToBeClickable(connections));
		conBtn.click();
		WebElement outlookBtn=wait.until(ExpectedConditions.elementToBeClickable(outlookCon));	
		outlookBtn.click();
		WebElement addBtn = wait.until(ExpectedConditions.elementToBeClickable(addCon));
		addBtn.click();
	}
	
	public void generateMeetingLink()
	{
		//WebElement promptField=driver.findElement(By.xpath("//textarea[@id='synoptix-message-input']"));
		WebElement promptField=driver.findElement(promptFieldLoc);
		promptField.click();
		promptField.sendKeys("Generate a meeting link for discussing project demo with Hasham and Roheen at 9 AM tomorrow");
		WebElement sendButton=driver.findElement(sendBtnLoc);
		sendButton.click();
		
	// Step 3: Wait for AI to generate Outlook button
        WebElement meetingLinkButton = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[normalize-space()='Review and send']")));
       // meetingLinkButton.click();
        Assert.assertTrue(meetingLinkButton.isDisplayed(), "Meeting link not generated by AI!");

		
		
	}
	public void draftEmail()
	{
		WebElement promptField=driver.findElement((promptFieldLoc));
		promptField.click();
		promptField.sendKeys("Draft an email to my manager with email address “asif.ali@gmail.com”  and with subject “Project Update” to inform him  about project status that Project  is 80% complete, expected finish by Friday");
		WebElement sendButton=driver.findElement(By.cssSelector("img[alt='Send']"));
		sendButton.click();
		
	// Step 3: Wait for AI to generate Outlook button
        WebElement meetingLinkButton = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("(//a[@href='mailto:asif.ali@gmail.com'][normalize-space()='asif.ali@gmail.com'])[1]")));
       // meetingLinkButton.click();
        Assert.assertTrue(meetingLinkButton.isDisplayed(), "Email got drafted");
	}
	
	
	
	
	
}
