package SynoptixAI.Pages;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

public class xPost {
	WebDriver driver;
	WebDriverWait wait;
	private By connections=By.cssSelector("img[alt='Connections']");
	private By tools=By.xpath("//button[normalize-space()='Tools']");
	private By xCon=By.cssSelector("p[title='Generate X (Twitter) posts.']");
	private By addCon=By.xpath("(//button[normalize-space()='Add (1)'])[1]");
	private By newChatBtnLoc=By.xpath("//span[normalize-space()='New Chat']");
	private By promptFieldLoc=By.xpath("//textarea[@id='synoptix-message-input']");
	private By sendBtnLoc=By.cssSelector("img[alt='Send']");

	public xPost(WebDriver driver) {
		this.driver = driver;
		this.wait = new WebDriverWait(driver, Duration.ofSeconds(30));

	}

	public void turnOnXTool() {

		WebElement newChatBtn=wait.until(ExpectedConditions.elementToBeClickable(newChatBtnLoc));
		newChatBtn.click();
		WebElement conBtn = wait.until(ExpectedConditions.elementToBeClickable(connections));
		conBtn.click();
		WebElement toolBtn = wait.until(ExpectedConditions.elementToBeClickable(tools));
		toolBtn.click();
		WebElement xConBtn=wait.until(ExpectedConditions.elementToBeClickable(xCon));	
		xConBtn.click();
		WebElement addBtn = wait.until(ExpectedConditions.elementToBeClickable(addCon));
		addBtn.click();
	}
	
	public void createPost()
	{
	
		WebElement promptField=driver.findElement(promptFieldLoc);
		promptField.click();
		promptField.sendKeys("Make an X post on Gaming with more emojis");
		WebElement sendButton=driver.findElement(sendBtnLoc);
		sendButton.click();
		
	// Step 3: Wait for AI to generate Outlook button
        WebElement postButton = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[normalize-space()='Review and Post']")));
       // meetingLinkButton.click();
        Assert.assertTrue(postButton.isDisplayed(), "X Post generated by AI!");

		
		
	}
	
	

}
